# Generated by Django 3.0.3 on 2020-03-18 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataCall', '0003_authorexample'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorExample',
        ),
    ]
