# Generated by Django 3.0.3 on 2020-04-25 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataCall', '0009_authorexample'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorExample',
        ),
    ]
