# Generated by Django 3.0.3 on 2020-04-05 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DataCall', '0004_delete_authorexample'),
    ]

    operations = [
        migrations.CreateModel(
            name='enduser',
            fields=[
                ('userid', models.AutoField(db_column='userid', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', max_length=50)),
                ('userfname', models.CharField(db_column='userfname', max_length=50)),
                ('userlname', models.CharField(db_column='userlname', max_length=50)),
                ('userknowledgelevel', models.IntegerField(blank=True, db_column='userknowledgelevel', null=True)),
            ],
            options={
                'db_table': 'enduser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='userinformation',
            fields=[
                ('informationid', models.AutoField(db_column='informationid', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'userinformation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='userrecommendations',
            fields=[
                ('recomendationid', models.AutoField(db_column='recommendationid', primary_key=True, serialize=False)),
                ('bookid', models.ForeignKey(db_column='bookid', on_delete=django.db.models.deletion.DO_NOTHING, to='DataCall.Books')),
                ('userid', models.ForeignKey(db_column='enduser', on_delete=django.db.models.deletion.DO_NOTHING, to='Recommendations.enduser')),
            ],
            options={
                'db_table': 'userinformation',
                'managed': True,
            },
        ),
    ]
