# Generated by Django 3.0.3 on 2020-04-25 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userrecommendations',
            table='userrecommendations',
        ),
    ]
